[pairs]
excluded = [
    "1088620_R",
    "1093552_R",
    "1214871_R",
    "1244210_L",
    "1280269_R",
    "1282227_L",
    "2316554_R",
    "2823294_R",
    "2073708_R",
    "2089118_L",
    "2447132_R",
    "2618314_L",
    "3099401_L",
    "3099401_R",
    "3171181_L",
    "3225404_R",
    "3277846_R",
    "3283911_R",
    "3367506_L",
    "3398452_R",
    "3507011_R",
    "3686742_R",
    "3831536_L",
    "3911059_R",
    "3914068_L",
    "3942322_L",
    "3966908_L",
    "4016816_L",
    "4036096_L",
    "4072856_R",
    "4101162_R",
    "4101735_R",
    "4183260_L",
    "4319904_L",
    "4455888_L",
    "4515791_R",
]

[dataset]
root = "/config/workspace/public-hdd/dataset-tha"

[train]
root = "/config/workspace/public-ssd/train-tha"

[train.vae]
use_amp = true
num_workers = 8
num_epochs = 200
warmup_epochs = 5
val_interval = 1
batch_size = 12
patch_size = [128, 128, 128]
sw_batch_size = 12
lr_g = 0.0001
lr_d = 0.0002
adversarial_weight = 0.05
perceptual_weight = 0.3
eikonal_weight = 0.15
mse_weight = 3.0
solid_weight = 5.0
kl_weight = 0.03

[train.rflow]
use_amp = true
resume = false
num_workers = 8
num_epochs = 1000
val_interval = 1
batch_size = 12                # 随单卡显存变化，3D 扩散很需要大 Batch 的均值效应
effective_batch_size = 12      # 不随显存变化，显存不足时退化到梯度累积
sw_batch_size = 12
lr = 0.0001
ema_decay = 0.999
classifier_free_guidance = 3.0

[val]
3239892_L = "Stryker Accolade TMZF"
3308978_L = "Stryker Accolade TMZF"
3113806_L = "Stryker Accolade TMZF"
3252196_L = "Stryker Accolade TMZF"
1101905_R = "Stryker Accolade TMZF"
3579563_L = "Stryker Accolade TMZF"
2886532_L = "Stryker Accolade TMZF"
3720496_L = "Stryker Accolade TMZF"
4042056_R = "Stryker Accolade TMZF"
2895596_R = "Stryker Accolade TMZF"
2915673_L = "DePuy Corail"
4472156_L = "DePuy Corail"
3753952_R = "DePuy Corail"
4336182_R = "DePuy Corail"
2398447_R = "DePuy Corail"
4309708_R = "DePuy Corail"
4228899_R = "DePuy Corail"
3742567_L = "DePuy Corail"
3065364_R = "DePuy Corail"
1050562_L = "DePuy Corail"
4022129_L = "DePuy SUMMIT"
3894711_L = "DePuy SUMMIT"
2712052_R = "DePuy SUMMIT"
2846450_L = "DePuy SUMMIT"
4210212_L = "DePuy SUMMIT"
1128417_R = "DePuy SUMMIT"
1466301_L = "DePuy SUMMIT"
3163754_L = "DePuy SUMMIT"
3442905_L = "DePuy SUMMIT"
4395167_L = "DePuy SUMMIT"
3857630_R = "DePuy Tri-Lock"
3306444_R = "DePuy Tri-Lock"
3958935_L = "DePuy Tri-Lock"
2609599_L = "DePuy Tri-Lock"
3353658_R = "DePuy Tri-Lock"
3603600_R = "DePuy Tri-Lock"
3633375_R = "DePuy Tri-Lock"
1393755_R = "DePuy Tri-Lock"
3384299_R = "DePuy Tri-Lock"
3353666_R = "DePuy Tri-Lock"
2093957_L = "Stryker Secur-Fit"
1811931_L = "Stryker Secur-Fit"
3928515_L = "Stryker Secur-Fit"
1183152_L = "Stryker Secur-Fit"
3708668_R = "Stryker Secur-Fit"
3256558_L = "Stryker Secur-Fit"
4124765_R = "Stryker Secur-Fit"
3844780_L = "Stryker Secur-Fit"
3663830_L = "Stryker Secur-Fit"
2574494_L = "Stryker Secur-Fit"
1837562_L = ""
4016923_R = ""
4132103_R = ""
3957200_R = ""
4147856_R = ""
3369765_R = ""
4498737_L = ""
2468227_R = ""
1467097_R = ""
1897858_R = ""
4052853_R = "Wagner Cone"
4183936_L = "Wagner Cone"
2331898_R = "Wagner Cone"
3146163_L = "Wagner Cone"
3130869_L = "Wagner Cone"
2783619_L = "Wagner Cone"
3938760_R = "Wagner Cone"
3256561_L = "Wagner Cone"
4071146_R = "Wagner Cone"
3898958_L = "Wagner Cone"
3610947_R = "Zimmer Wagner SL"
3910455_L = "Zimmer Wagner SL"
3391762_L = "Zimmer Wagner SL"
2683281_L = "Zimmer M/L Taper"
3555543_L = "Zimmer M/L Taper"
3587430_L = "Zimmer M/L Taper"
4145881_R = "Zimmer M/L Taper"
3548410_L = "Zimmer M/L Taper"
3447365_L = "Zimmer M/L Taper"
3249284_L = "Zimmer M/L Taper"
3313805_L = "Zimmer M/L Taper"
3474329_L = "Zimmer M/L Taper"
4293989_L = "Zimmer M/L Taper"
2085724_L = "DePuy S-ROM"
4016818_R = "DePuy S-ROM"
4362512_R = "AK Medical ML-TP"

[test]
3881066_L = "Stryker Accolade TMZF"
3308978_R = "Stryker Accolade TMZF"
3113806_R = "Stryker Accolade TMZF"
4325878_L = "DePuy Corail"
4472156_R = "DePuy Corail"
4168878_L = "DePuy Corail"
4158331_R = "DePuy SUMMIT"
4201884_R = "DePuy SUMMIT"
3383410_R = "DePuy SUMMIT"
3361894_L = "DePuy Tri-Lock"
3185489_L = "DePuy Tri-Lock"
3958935_R = "DePuy Tri-Lock"
2093957_R = "Stryker Secur-Fit"
3288629_R = "Stryker Secur-Fit"
3896610_R = "Stryker Secur-Fit"
4157230_R = ""
3721610_R = ""
3324205_R = ""
2389918_L = "Wagner Cone"
4183936_R = "Wagner Cone"
4095220_L = "Wagner Cone"
3609353_L = "Zimmer Wagner SL"
3800225_R = "Zimmer Wagner SL"
4358483_R = "Zimmer Wagner SL"
2683281_R = "Zimmer M/L Taper"
4147666_L = "Zimmer M/L Taper"
3573802_R = "Zimmer M/L Taper"
3271325_R = "DePuy S-ROM"
3110518_R = "DePuy S-ROM"
